/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Cylinder000: THREE.Mesh
    Cylinder000_1: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube006_2: THREE.Mesh
    Cube006_3: THREE.Mesh
    Cube006_4: THREE.Mesh
    Cube006_5: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube015: THREE.Mesh
    Cube015_1: THREE.Mesh
    Cube015_2: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Blue: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Stone2: THREE.MeshStandardMaterial
    PinkLight: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
  }
}

export default function CharacterKnight(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/characters/character_knight.gltf')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 1.24, 0]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={nodes.Cylinder001_1.material} />
        <group position={[0, 0.31, 0.05]}>
          <mesh geometry={nodes.Cylinder000.geometry} material={nodes.Cylinder000.material} />
          <mesh geometry={nodes.Cylinder000_1.geometry} material={nodes.Cylinder000_1.material} />
        </group>
      </group>
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} />
      <mesh geometry={nodes.Cube006_1.geometry} material={nodes.Cube006_1.material} />
      <mesh geometry={nodes.Cube006_2.geometry} material={nodes.Cube006_2.material} />
      <mesh geometry={nodes.Cube006_3.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube006_4.geometry} material={materials.Blue} />
      <mesh geometry={nodes.Cube006_5.geometry} material={materials.White} />
      <group position={[0.2, 0.63, 0]}>
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={nodes.Cube005_1.material} />
        <mesh geometry={nodes.Cube005_2.geometry} material={nodes.Cube005_2.material} />
      </group>
      <group position={[-0.2, 0.63, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={nodes.Cube003_2.material} />
      </group>
      <group position={[0, 0.7, 0]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials.PinkLight} />
        <mesh geometry={nodes.Cube015_1.geometry} material={nodes.Cube015_1.material} />
        <mesh geometry={nodes.Cube015_2.geometry} material={materials.Beige} />
      </group>
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/characters/character_knight.gltf'))
