/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4504: THREE.Mesh
    Cube4504_1: THREE.Mesh
  }
  materials: {
    Metal: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
  }
}

export default function (props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('/shield_uncommonassets/kaykit/Models/items/.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4504.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube4504_1.geometry} material={materials.BrownDark} />
    </group>
  )
}

//useGLTF.preload(require('/shield_uncommonassets/kaykit/Models/items/.gltf.glb'))
