/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    BlueDark: THREE.MeshStandardMaterial
    BlueLight: THREE.MeshStandardMaterial
  }
}

export default function Banner(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/banner.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Plane002_1.geometry} material={materials.BlueDark} />
      <mesh geometry={nodes.Plane002_2.geometry} material={materials.BlueLight} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/banner.gltf.glb'))
