/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4422: THREE.Mesh
    Cube4422_1: THREE.Mesh
    Cube4422_2: THREE.Mesh
    Cube4422_3: THREE.Mesh
    Cube4422_4: THREE.Mesh
    Cube4422_5: THREE.Mesh
    Cube4422_6: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    PurpleDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    BlueDark: THREE.MeshStandardMaterial
    GreenDark: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
  }
}

export default function BookcaseFilledBroken(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/bookcaseFilled_broken.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4422.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube4422_1.geometry} material={materials.PurpleDark} />
      <mesh geometry={nodes.Cube4422_2.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube4422_3.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube4422_4.geometry} material={materials.BlueDark} />
      <mesh geometry={nodes.Cube4422_5.geometry} material={materials.GreenDark} />
      <mesh geometry={nodes.Cube4422_6.geometry} material={materials.WoodDark} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/bookcaseFilled_broken.gltf.glb'))
