/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4412: THREE.Mesh
    Cube4412_1: THREE.Mesh
    Cube4412_2: THREE.Mesh
  }
  materials: {
    StoneDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
  }
}

export default function BookA(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/bookA.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4412.geometry} material={materials.StoneDark} />
      <mesh geometry={nodes.Cube4412_1.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube4412_2.geometry} material={materials.Metal} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/bookA.gltf.glb')
