/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4448: THREE.Mesh
    Cube4448_1: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
  }
}

export default function CrossbowRare(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/crossbow_rare.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4448.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube4448_1.geometry} material={materials.Gold} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/crossbow_rare.gltf.glb')
