/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder280: THREE.Mesh
    Cylinder280_1: THREE.Mesh
  }
  materials: {
    Mud: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
  }
}

export default function PlateFull(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/plateFull.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder280.geometry} material={materials.Mud} />
      <mesh geometry={nodes.Cylinder280_1.geometry} material={materials.Beige} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/plateFull.gltf.glb'))
