/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder289: THREE.Mesh
    Cylinder289_1: THREE.Mesh
    Cylinder289_2: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
  }
}

export default function PotionLargeGreen(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/potionLarge_green.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder289.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Cylinder289_1.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cylinder289_2.geometry} material={materials.Green} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/potionLarge_green.gltf.glb')
