/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder292: THREE.Mesh
    Cylinder292_1: THREE.Mesh
    Cylinder292_2: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
  }
}

export default function PotionMediumGreen(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/potionMedium_green.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder292.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Cylinder292_1.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cylinder292_2.geometry} material={materials.Green} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/potionMedium_green.gltf.glb'))
