/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder293: THREE.Mesh
    Cylinder293_1: THREE.Mesh
    Cylinder293_2: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function PotionMediumRed(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/potionMedium_red.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder293.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Cylinder293_1.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cylinder293_2.geometry} material={materials.Red} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/potionMedium_red.gltf.glb'))
