/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4468: THREE.Mesh
    Cube4468_1: THREE.Mesh
    Cube4468_2: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    GreenDark: THREE.MeshStandardMaterial
  }
}

export default function QuiverHalfFull(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/quiver_half_full.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4468.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube4468_1.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube4468_2.geometry} material={materials.GreenDark} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/quiver_half_full.gltf.glb')
