/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4508: THREE.Mesh
    Cube4508_1: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    Purple: THREE.MeshStandardMaterial
  }
}

export default function StaffUncommon(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/staff_uncommon.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4508.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube4508_1.geometry} material={materials.Purple} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/staff_uncommon.gltf.glb'))
