/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4513: THREE.Mesh
    Cube4513_1: THREE.Mesh
    Cube4513_2: THREE.Mesh
    Cube4513_3: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Gold: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function SwordRare(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/sword_rare.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4513.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube4513_1.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube4513_2.geometry} material={materials.Gold} />
      <mesh geometry={nodes.Cube4513_3.geometry} material={materials.Red} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/sword_rare.gltf.glb'))
