/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube4526: THREE.Mesh
    Cube4526_1: THREE.Mesh
    Cube4526_2: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
  }
}

export default function TileSpikes(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/tileSpikes.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube4526.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube4526_1.geometry} material={materials.WoodDark} />
      <mesh geometry={nodes.Cube4526_2.geometry} material={materials.Metal} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/tileSpikes.gltf.glb')
