/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube023: THREE.Mesh
    Cube023_1: THREE.Mesh
    Cube023_2: THREE.Mesh
  }
  materials: {
    WoodDark: THREE.MeshStandardMaterial
    PurpleDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export default function SkeletonBow(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/skeleton_items/skeleton_bow.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube023.geometry} material={materials.WoodDark} />
      <mesh geometry={nodes.Cube023_1.geometry} material={materials.PurpleDark} />
      <mesh geometry={nodes.Cube023_2.geometry} material={materials.White} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/skeleton_items/skeleton_bow.gltf.glb')
