/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube030: THREE.Mesh
    Cube030_1: THREE.Mesh
    Cube030_2: THREE.Mesh
    Cube030_3: THREE.Mesh
  }
  materials: {
    ForestGreen: THREE.MeshStandardMaterial
    PurpleDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export default function SkeletonStaff(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/items/skeleton_items/skeleton_staff.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube030.geometry} material={materials.ForestGreen} />
      <mesh geometry={nodes.Cube030_1.geometry} material={materials.PurpleDark} />
      <mesh geometry={nodes.Cube030_2.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube030_3.geometry} material={materials.Black} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/items/skeleton_items/skeleton_staff.gltf.glb'))
