/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube7714: THREE.Mesh
    Cube7714_1: THREE.Mesh
    eyes: THREE.Mesh
    jaw: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Glow: THREE.MeshStandardMaterial
  }
}

export default function Skull(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('/skull.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Cube7714"
        geometry={nodes.Cube7714.geometry}
        material={nodes.Cube7714.material}
        morphTargetDictionary={nodes.Cube7714.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube7714.morphTargetInfluences}
      />
      <mesh
        name="Cube7714_1"
        geometry={nodes.Cube7714_1.geometry}
        material={materials.Black}
        morphTargetDictionary={nodes.Cube7714_1.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube7714_1.morphTargetInfluences}
      />
      <mesh geometry={nodes.eyes.geometry} material={materials.Glow} position={[0, 0.42, 0.26]} />
      <mesh geometry={nodes.jaw.geometry} material={nodes.jaw.material} position={[0, 0.13, 0.04]} />
    </group>
  )
}

//useGLTF.preload(require('/skull.glb')
