/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube034: THREE.Mesh
    Cube034_1: THREE.Mesh
    Cube034_2: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
    Stone2: THREE.MeshStandardMaterial
  }
}

export default function SwordBrokenHalf(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/items/skeleton_items/sword_broken_half.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube034.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube034_1.geometry} material={materials.WoodDark} />
      <mesh geometry={nodes.Cube034_2.geometry} material={materials.Stone2} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/items/skeleton_items/sword_broken_half.gltf.glb')
