/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube7654: THREE.Mesh
    Cube7654_1: THREE.Mesh
    Cube7654_2: THREE.Mesh
    Cube7654_3: THREE.Mesh
    Cube7655: THREE.Mesh
    Cube7655_1: THREE.Mesh
    Cube7653: THREE.Mesh
    Cube7653_1: THREE.Mesh
    Cube7650: THREE.Mesh
    Cube7650_1: THREE.Mesh
    character_skeleton_minion_eyes: THREE.Mesh
    character_skeleton_minion_jaw: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Glow: THREE.MeshStandardMaterial
  }
}

export default function CharacterSkeletonMinion(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/characters/skeletons/character_skeleton_minion.gltf') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube7654.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube7654_1.geometry} material={nodes.Cube7654_1.material} />
      <mesh geometry={nodes.Cube7654_2.geometry} material={nodes.Cube7654_2.material} />
      <mesh geometry={nodes.Cube7654_3.geometry} material={materials.Metal} />
      <group position={[0.2, 0.63, 0]}>
        <mesh geometry={nodes.Cube7655.geometry} material={nodes.Cube7655.material} />
        <mesh geometry={nodes.Cube7655_1.geometry} material={nodes.Cube7655_1.material} />
      </group>
      <group position={[-0.2, 0.63, 0]}>
        <mesh geometry={nodes.Cube7653.geometry} material={nodes.Cube7653.material} />
        <mesh geometry={nodes.Cube7653_1.geometry} material={nodes.Cube7653_1.material} />
      </group>
      <group position={[0, 0.7, 0]}>
        <mesh
          name="Cube7650"
          geometry={nodes.Cube7650.geometry}
          material={nodes.Cube7650.material}
          morphTargetDictionary={nodes.Cube7650.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube7650.morphTargetInfluences}
        />
        <mesh
          name="Cube7650_1"
          geometry={nodes.Cube7650_1.geometry}
          material={nodes.Cube7650_1.material}
          morphTargetDictionary={nodes.Cube7650_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Cube7650_1.morphTargetInfluences}
        />
        <mesh
          geometry={nodes.character_skeleton_minion_eyes.geometry}
          material={materials.Glow}
          position={[0, 0.42, 0.26]}
        />
        <mesh
          geometry={nodes.character_skeleton_minion_jaw.geometry}
          material={nodes.character_skeleton_minion_jaw.material}
          position={[0, 0.13, 0.04]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/characters/skeletons/character_skeleton_minion.gltf')
