/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube3996: THREE.Mesh
    Cube3996_1: THREE.Mesh
    Cube3996_2: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Mud: THREE.MeshStandardMaterial
  }
}

export default function BarbarianHeadB(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/characters/extra_heads/barbarianHeadB.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube3996.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Cube3996_1.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube3996_2.geometry} material={materials.Mud} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/characters/extra_heads/barbarianHeadB.gltf.glb')
