/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube3997: THREE.Mesh
    Cube3997_1: THREE.Mesh
    Cube3997_2: THREE.Mesh
  }
  materials: {
    Beige: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
  }
}

export default function BarbarianHeadC(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/characters/extra_heads/barbarianHeadC.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube3997.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cube3997_1.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube3997_2.geometry} material={materials.WoodDark} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/characters/extra_heads/barbarianHeadC.gltf.glb'))
