/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube3998: THREE.Mesh
    Cube3998_1: THREE.Mesh
    Cube3998_2: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
  }
}

export default function KnightHeadA(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/characters/extra_heads/knightHeadA.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube3998.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube3998_1.geometry} material={nodes.Cube3998_1.material} />
      <mesh geometry={nodes.Cube3998_2.geometry} material={nodes.Cube3998_2.material} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/characters/extra_heads/knightHeadA.gltf.glb'))
