/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube3533: THREE.Mesh
    Cube3533_1: THREE.Mesh
    Cube3533_2: THREE.Mesh
    Cube3532: THREE.Mesh
    Cube3532_1: THREE.Mesh
  }
  materials: {
    BrownDark: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    Red: THREE.MeshStandardMaterial
  }
}

export default function MageHeadA(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/characters/extra_heads/mageHeadA.gltf') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube3533.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube3533_1.geometry} material={nodes.Cube3533_1.material} />
      <mesh geometry={nodes.Cube3533_2.geometry} material={nodes.Cube3533_2.material} />
      <mesh geometry={nodes.Cube3532.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube3532_1.geometry} material={materials.Red} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/characters/extra_heads/mageHeadA.gltf')
