/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube1011: THREE.Mesh
    Cube1011_1: THREE.Mesh
    Cube1011_2: THREE.Mesh
    Cube1011_3: THREE.Mesh
    Cube1011_4: THREE.Mesh
    Cube1011_5: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    StoneDark: THREE.MeshStandardMaterial
  }
}

export default function Barracks(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/objects/gltf/barracks.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube1011.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Cube1011_1.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube1011_2.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube1011_3.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube1011_4.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cube1011_5.geometry} material={materials.StoneDark} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/objects/gltf/barracks.gltf.glb')
