/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder1300: THREE.Mesh
    Cylinder1300_1: THREE.Mesh
    Cylinder1300_2: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
  }
}

export default function BridgeRoofed(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/objects/gltf/bridge_roofed.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder1300.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cylinder1300_1.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Cylinder1300_2.geometry} material={materials.BrownDark} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/objects/gltf/bridge_roofed.gltf.glb'))
