/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube1012: THREE.Mesh
    Cube1012_1: THREE.Mesh
    Cube1012_2: THREE.Mesh
    Cube1012_3: THREE.Mesh
    Cube1012_4: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    StoneDark: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
  }
}

export default function Castle(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/objects/gltf/castle.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube1012.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube1012_1.geometry} material={materials.StoneDark}/>
      <mesh geometry={nodes.Cube1012_2.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube1012_3.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Cube1012_4.geometry} material={materials.White} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/objects/gltf/castle.gltf.glb'))
