/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder1302: THREE.Mesh
    Cylinder1302_1: THREE.Mesh
    Cylinder1302_2: THREE.Mesh
  }
  materials: {
    GreenDark: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
  }
}

export default function DetailForestB(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/objects/gltf/detail_forestB.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder1302.geometry} material={materials.GreenDark} />
      <mesh geometry={nodes.Cylinder1302_1.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cylinder1302_2.geometry} material={materials.Stone} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/objects/gltf/detail_forestB.gltf.glb')
