/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder756: THREE.Mesh
    Cylinder756_1: THREE.Mesh
    Cylinder756_2: THREE.Mesh
    Cylinder756_3: THREE.Mesh
    Cylinder756_4: THREE.Mesh
    Cylinder757: THREE.Mesh
    Cylinder757_1: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    Stone: THREE.MeshStandardMaterial
  }
}

export default function Mill(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/objects/gltf/mill.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder756.geometry} material={nodes.Cylinder756.material} />
      <mesh geometry={nodes.Cylinder756_1.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Cylinder756_2.geometry} material={nodes.Cylinder756_2.material} />
      <mesh geometry={nodes.Cylinder756_3.geometry} material={materials.White} />
      <mesh geometry={nodes.Cylinder756_4.geometry} material={materials.Stone} />
      <group position={[0, 1.27, 0.17]}>
        <mesh geometry={nodes.Cylinder757.geometry} material={nodes.Cylinder757.material} />
        <mesh geometry={nodes.Cylinder757_1.geometry} material={nodes.Cylinder757_1.material} />
      </group>
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/objects/gltf/mill.gltf.glb'))
