/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube1022: THREE.Mesh
    Cube1022_1: THREE.Mesh
    Cube1022_2: THREE.Mesh
    Cube1022_3: THREE.Mesh
    Cube1022_4: THREE.Mesh
    Cube1022_5: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Black: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    WoodDark: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
  }
}

export default function Mine(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/assets/kaykit/Models/objects/gltf/mine.gltf.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube1022.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube1022_1.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cube1022_2.geometry} material={materials.Black} />
      <mesh geometry={nodes.Cube1022_3.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube1022_4.geometry} material={materials.WoodDark} />
      <mesh geometry={nodes.Cube1022_5.geometry} material={materials.Beige} />
    </group>
  )
}

useGLTF.preload('/assets/kaykit/Models/objects/gltf/mine.gltf.glb')
