/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cube403: THREE.Mesh
    Cube403_1: THREE.Mesh
    Cube403_2: THREE.Mesh
    Cube403_3: THREE.Mesh
    watermill_wheel: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    White: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
  }
}

export default function Watermill(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/objects/gltf/watermill.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube403.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cube403_1.geometry} material={materials.White} />
      <mesh geometry={nodes.Cube403_2.geometry} material={nodes.Cube403_2.material} />
      <mesh geometry={nodes.Cube403_3.geometry} material={materials.Brown} />
      <mesh
        geometry={nodes.watermill_wheel.geometry}
        material={nodes.watermill_wheel.material}
        position={[-0.19, 0, 0]}
      />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/objects/gltf/watermill.gltf.glb'))
