/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder1311: THREE.Mesh
    Cylinder1311_1: THREE.Mesh
    Cylinder1311_2: THREE.Mesh
    Cylinder1311_3: THREE.Mesh
    Cylinder1311_4: THREE.Mesh
    Cylinder1311_5: THREE.Mesh
  }
  materials: {
    Stone: THREE.MeshStandardMaterial
    StoneDark: THREE.MeshStandardMaterial
    BrownDark: THREE.MeshStandardMaterial
    Brown: THREE.MeshStandardMaterial
    Water: THREE.MeshStandardMaterial
    Beige: THREE.MeshStandardMaterial
  }
}

export default function Well(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(require('../../../../../public/assets/kaykit/Models/objects/gltf/well.gltf.glb')) as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder1311.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Cylinder1311_1.geometry} material={materials.StoneDark} />
      <mesh geometry={nodes.Cylinder1311_2.geometry} material={materials.BrownDark} />
      <mesh geometry={nodes.Cylinder1311_3.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Cylinder1311_4.geometry} material={materials.Water} />
      <mesh geometry={nodes.Cylinder1311_5.geometry} material={materials.Beige} />
    </group>
  )
}

//useGLTF.preload(require('../../../../../public/assets/kaykit/Models/objects/gltf/well.gltf.glb'))
